Add support for selectedBackgroundColor
yonat/MultiSelectSegmentedControl pull request #31
Opened 2019-10-02 17:09 UTC by jemise111

Fixes #30

2019-10-02 17:34 UTC, yonat requested changes
Nice, thanks!

Please use the `parent.selectedBackgroundColor` instead of copying it to each segment -- similar to `titleTextAttributes`. (You'll need to remove the `private` from `MultiSelectSegment.updateColors()` so you can call it when the parent's color changes.)

2019-10-02 18:50 UTC, jemise111 commented
@yonat changes made! Also left a note in the Readme

2019-10-03 07:05 UTC, yonat commented on Sources/MultiSelectSegmentedControl.swift
> +    @objc public var selectedBackgroundColor: UIColor? {
Forgot to mention:

Please make this an `@IBInspectable open dynamic var` To support Interface Builder and UIAppearance.

Thanks!

2019-10-03 12:41 UTC, yonat commented on Sources/MultiSelectSegmentedControl.swift
> +    @objc public var selectedBackgroundColor: UIColor? {
Also, please move it to the end of the `Appearance` mark.
If you prefer, grant me [edit access to the PR](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) and I'll do these little fixes.)

2019-10-03 14:32 UTC, jemise111 commented
@yonat done! I think I enabled you to make edits too in case there's anything else

2019-10-03 17:09 UTC, merged

2019-10-03 17:11 UTC, yonat commented
Thanks!

2023-10-25 09:24 UTC, yonat commented
@CodiumAI-Agent /review

2023-10-25 09:24 UTC, CodiumAI-Agent commented
## PR Analysis

- 🎯 **Main theme:** Adding a new feature to support selectedBackgroundColor in the MultiSelectSegmentedControl.
- 📝 **PR summary:** This PR introduces a new feature that allows users to set a selectedBackgroundColor for the MultiSelectSegmentedControl. The selectedBackgroundColor can be different from the tintColor. The PR also includes updates to the README to document this new feature.
- 📌 **Type of PR:** Enhancement
- 🧪 **Relevant tests added:** No
- ⏱️ **Estimated effort to review [1-5]:** 2, because the PR is relatively small and straightforward. It introduces a new feature and updates the documentation accordingly.
- 🔒 **Security concerns:** No
## PR Feedback

- 💡 **General suggestions:** The PR is well-structured and the code changes are clear. However, it would be beneficial to include tests for the new feature to ensure it works as expected and does not introduce any regressions.


- **<details><summary> 🤖 Code feedback:**</summary>


  - **relevant file:** ``Sources/MultiSelectSegment.swift``
   **suggestion:** Consider making the updateColors() function private again and call it from the didSet of the selectedBackgroundColor property. This way, the function can't be called from outside and the encapsulation is preserved. [important]
   **relevant line:** [func updateColors() {](https://github.com/yonat/MultiSelectSegmentedControl/pull/31/files#diff-6cd028f150afd33ed13addcb099dd9eef6acd88e292382b9f1878ce5e77616d5R139)


  - **relevant file:** ``Sources/MultiSelectSegmentedControl.swift``
   **suggestion:** It would be beneficial to add a default value for selectedBackgroundColor to avoid potential null pointer exceptions. [medium]
   **relevant line:** [@IBInspectable open dynamic var selectedBackgroundColor: UIColor? {](https://github.com/yonat/MultiSelectSegmentedControl/pull/31/files#diff-4662c64ff51c6056203b79b655005a51e401e7888efaf4ed69ecc2b4362b5023R140)

</details>


### How to use
> Tag me in a comment '@CodiumAI-Agent' and add one of the following commands:
> **/review [-i]**: Request a review of your Pull Request. For an incremental review, which only considers changes since the last review, include the '-i' option.
> **/describe**: Modify the PR title and description based on the contents of the PR.
> **/improve [--extended]**: Suggest improvements to the code in the PR. Extended mode employs several calls, and provides a more thorough feedback. 
> **/ask \<QUESTION\>**: Pose a question about the PR.
> **/update_changelog**: Update the changelog based on the PR's contents.

>To edit any configuration parameter from **configuration.toml**, add --config_path=new_value
>For example: /review --pr_reviewer.extra_instructions="focus on the file: ..." 
>To list the possible configuration parameters, use the **/config** command.